version: '3.7'

services:
  udagram-api-feed:
    image: nitincherian/udagram-api-feed
    build: 
      context: ./udagram-api-feed
      args:
        - POSTGRES_USERNAME=$POSTGRES_USERNAME
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_HOST=$POSTGRES_HOST
        - POSTGRES_DB=$POSTGRES_DB
        - AWS_BUCKET=$AWS_BUCKET
        - AWS_REGION=$AWS_REGION 
        - AWS_PROFILE=$AWS_PROFILE
        - JWT_SECRET=$JWT_SECRET
        - URL=$URL

  udagram-api-users:
    image: nitincherian/udagram-api-users
    build: 
      context: ./udagram-api-users
      args:
        - POSTGRES_USERNAME=$POSTGRES_USERNAME
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_HOST=$POSTGRES_HOST
        - POSTGRES_DB=$POSTGRES_DB
        - AWS_BUCKET=$AWS_BUCKET
        - AWS_REGION=$AWS_REGION 
        - AWS_PROFILE=$AWS_PROFILE
        - JWT_SECRET=$JWT_SECRET
        - URL=$URL

  udagram-frontend:
    image: nitincherian/udagram-frontend
    build: ./udagram-frontend

  udagram-reverse-proxy:
    image: nitincherian/udagram-reverse-proxy
    build: ./udagram-reverse-proxy
